package gest;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

public class home extends javax.swing.JFrame {
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); //To change body of generated methods, choose Tools | Templates.
    }
    public home() {
        initComponents();
    
       /* Toolkit tool=Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int heigth = (int) dim.getHeight();
        int width = (int)  dim.getWidth();
        setSize(width,heigth);
        setLocation(width / 2 - getWidth() / 2,heigth / 2 - getHeight() / 2);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnajouter = new javax.swing.JPanel();
        iditlabelicon = new javax.swing.JLabel();
        btnmodifier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsupprimer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnuser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titelpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cpanel = new javax.swing.JPanel();
        Spanelmodifier = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(220, 150));
        setUndecorated(true);

        bgpanel.setBackground(new java.awt.Color(255, 255, 255));
        bgpanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bgpanelFocusLost(evt);
            }
        });

        sidepanel.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/gg_stock.png"))); // NOI18N

        btnajouter.setBackground(new java.awt.Color(204, 0, 51));
        btnajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnajouterMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnajouterMousePressed(evt);
            }
        });

        iditlabelicon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iditlabelicon.setForeground(new java.awt.Color(255, 255, 255));
        iditlabelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-plus-32.png"))); // NOI18N
        iditlabelicon.setText("Ajouter un produit");

        javax.swing.GroupLayout btnajouterLayout = new javax.swing.GroupLayout(btnajouter);
        btnajouter.setLayout(btnajouterLayout);
        btnajouterLayout.setHorizontalGroup(
            btnajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnajouterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iditlabelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnajouterLayout.setVerticalGroup(
            btnajouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iditlabelicon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnmodifier.setBackground(new java.awt.Color(204, 0, 51));
        btnmodifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmodifierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmodifierMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-modifier-la-propriété-26.png"))); // NOI18N
        jLabel1.setText("Modifier un produit");

        javax.swing.GroupLayout btnmodifierLayout = new javax.swing.GroupLayout(btnmodifier);
        btnmodifier.setLayout(btnmodifierLayout);
        btnmodifierLayout.setHorizontalGroup(
            btnmodifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmodifierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnmodifierLayout.setVerticalGroup(
            btnmodifierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnsupprimer.setBackground(new java.awt.Color(204, 0, 51));
        btnsupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnsupprimerMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-annuler-32.png"))); // NOI18N
        jLabel2.setText("supprimer un produit");

        javax.swing.GroupLayout btnsupprimerLayout = new javax.swing.GroupLayout(btnsupprimer);
        btnsupprimer.setLayout(btnsupprimerLayout);
        btnsupprimerLayout.setHorizontalGroup(
            btnsupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsupprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnsupprimerLayout.setVerticalGroup(
            btnsupprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        btnuser.setBackground(new java.awt.Color(204, 0, 51));
        btnuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnuserMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-administrateur-homme-filled-34.png"))); // NOI18N
        jLabel3.setText("Utilisateurs");

        javax.swing.GroupLayout btnuserLayout = new javax.swing.GroupLayout(btnuser);
        btnuser.setLayout(btnuserLayout);
        btnuserLayout.setHorizontalGroup(
            btnuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnuserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnuserLayout.setVerticalGroup(
            btnuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jSeparator1.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnmodifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        titelpanel.setBackground(new java.awt.Color(204, 0, 51));

        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("chez GestParc _______________________________________");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextField1.setSelectionColor(new java.awt.Color(204, 0, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-chercher-20.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("bienvenue sur votre stock");

        javax.swing.GroupLayout titelpanelLayout = new javax.swing.GroupLayout(titelpanel);
        titelpanel.setLayout(titelpanelLayout);
        titelpanelLayout.setHorizontalGroup(
            titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titelpanelLayout.createSequentialGroup()
                .addGap(0, 157, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(titelpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titelpanelLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel7)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );
        titelpanelLayout.setVerticalGroup(
            titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titelpanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(titelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titelpanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gest/images/icons8-effacer-25.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("yassine youcefi");

        Spanelmodifier.setMaximumSize(new java.awt.Dimension(452, 402));
        Spanelmodifier.setMinimumSize(new java.awt.Dimension(452, 402));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5ab545363deb298a91807476", "iphone5",  new Integer(1),  new Float(40000.0),  new Integer(2), "appel", "5", "5ac0f7ab0632416701c90714"},
                {"5ab545563deb298a9180747c", "iphone6",  new Integer(1),  new Float(50000.0),  new Integer(3), "appel", "6", "5ac0f7ab0632416701c90714"},
                {"5ab545ab3deb298a91807482", "galaxy s6",  new Integer(1),  new Float(45000.0),  new Integer(2), "samsung", "6", "5ac0f7ab0632416701c90714"},
                {"5ab545cf3deb298a91807488", "galaxy s7",  new Integer(1),  new Float(55000.0),  new Integer(1), "samsung", "7", "5acf7ede124f40e2e4de7f1c"}
            },
            new String [] {
                "Id", "Nom", "Numéro", "Prix", "Quantité", "Marque", "Model", "Id fournisseure"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(204, 0, 51));
        Spanelmodifier.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        }

        javax.swing.GroupLayout cpanelLayout = new javax.swing.GroupLayout(cpanel);
        cpanel.setLayout(cpanelLayout);
        cpanelLayout.setHorizontalGroup(
            cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Spanelmodifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cpanelLayout.setVerticalGroup(
            cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Spanelmodifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgpanelLayout = new javax.swing.GroupLayout(bgpanel);
        bgpanel.setLayout(bgpanelLayout);
        bgpanelLayout.setHorizontalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(titelpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bgpanelLayout.setVerticalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(titelpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(bgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel6MousePressed

    private void bgpanelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bgpanelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bgpanelFocusLost

    private void btnajouterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajouterMousePressed
        // TODO add your handling code here:
        setColor(btnajouter);
        resetColor(btnmodifier);
        resetColor(btnsupprimer);
        resetColor(btnuser);
    }//GEN-LAST:event_btnajouterMousePressed

    private void btnmodifierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodifierMousePressed
        // TODO add your handling code here:
        setColor(btnmodifier);
        resetColor(btnajouter);
        resetColor(btnsupprimer);
        resetColor(btnuser);
    }//GEN-LAST:event_btnmodifierMousePressed

    private void btnsupprimerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsupprimerMousePressed
        // TODO add your handling code here:
        setColor(btnsupprimer);
        resetColor(btnmodifier);
        resetColor(btnajouter);
        resetColor(btnuser);
    }//GEN-LAST:event_btnsupprimerMousePressed

    private void btnuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuserMousePressed
        // TODO add your handling code here:
        setColor(btnuser);
        resetColor(btnajouter);
        resetColor(btnsupprimer);
         resetColor(btnmodifier);
    }//GEN-LAST:event_btnuserMousePressed

    private void btnmodifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodifierMouseClicked
        // TODO add your handling code here:
        //removingpanel
       cpanel.removeAll();
        cpanel.repaint();
        cpanel.revalidate();
 
        //addingpanel
        
       cpanel.add(Spanelmodifier);
        cpanel.repaint();
        cpanel.revalidate();
    }//GEN-LAST:event_btnmodifierMouseClicked

    private void btnajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnajouterMouseClicked
        // TODO add your handling code here:
        //removingpanel
        cpanel.removeAll();
        cpanel.repaint();
        cpanel.revalidate();
 
        //addingpanel
        Spanelajouter s = new Spanelajouter();
        System.out.println(s);
        cpanel.add(s);
        cpanel.repaint();
        cpanel.revalidate();
        
        
    }//GEN-LAST:event_btnajouterMouseClicked


    void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(255,51,51));
        
    }
   
    void resetColor(JPanel panel){
    
        panel.setBackground(new java.awt.Color( 204,0,51));  
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(() -> {
            new home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Spanelmodifier;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JPanel btnajouter;
    private javax.swing.JPanel btnmodifier;
    private javax.swing.JPanel btnsupprimer;
    private javax.swing.JPanel btnuser;
    private javax.swing.JPanel cpanel;
    private javax.swing.JLabel iditlabelicon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel titelpanel;
    // End of variables declaration//GEN-END:variables
}
